name: Build and deploy Python app to Azure Web App - michaeldevbooklanding

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
      

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest names pylint
        
    - name: Pytest
      run: |
        pytest
        
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.8'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'michaeldevbooklanding'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0f7b91d632f041db8eb76107ef7caa5a }}
